services:
  mysql:
    image: mysql:8.0
    container_name: garage_db
    restart: always
    environment:
      MYSQL_DATABASE: garage_db
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - ./configs/garage.sql:/docker-entrypoint-initdb.d/garage.sql
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: